# Site settings
title:       Timothy Gu
email:       timothygu99@gmail.com
author:      Timothy Gu
description: "The hub for all things Timothy Gu."
baseurl:     ""
url:         ""

# Google analytics
google_analytics: "UA-60010707-1"

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus
disqus_shortname: timothygu-github

# Social icons
show_social_icons: true
github_username: TimothyGu
bitbucket_username: TimothyGu
stackoverflow_id:
twitter_username: Timothy__Gu
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:
instagram_username: Timothy_Gu

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:year/:month/:day/:title/
paginate:     3
sass:
  compressed: true
